package com.example.opsc_6311_poe_prototype_v2;
import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.cardview.widget.CardView
import com.example.opsc_6311_poe_prototype_v2.Catagories
import com.example.opsc_6311_poe_prototype_v2.R
import com.google.firebase.database.FirebaseDatabase

class CategoriesActivity : AppCompatActivity() {
    private lateinit var goToAddCategories: Button
    private lateinit var categoryListLayout: LinearLayout
    private lateinit var username: String
    private lateinit var textView : TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_categories)

        username = intent.getStringExtra("username") ?: ""

        categoryListLayout = findViewById(R.id.categoryListLayout)
        goToAddCategories = findViewById(R.id.goToAddCategoryBtn)

        goToAddCategories.setOnClickListener {
            showAddCategoryDialog()
        }
        findViewById<Button>(R.id.goToManageBudgetBtn).setOnClickListener {
            startActivity(Intent(this, ManageBudgetActivity::class.java).putExtra("username", username))
        }
        findViewById<Button>(R.id.goToAnalysisBtn).setOnClickListener {
            startActivity(Intent(this, AnalysisActivity::class.java).putExtra("username", username))
        }

        findViewById<Button>(R.id.goToCategoriesBtn).setOnClickListener {
            startActivity(Intent(this, CategoriesActivity::class.java).putExtra("username", username))
        }
        findViewById<Button>(R.id.goToHome).setOnClickListener {
            startActivity(Intent(this, MainActivity::class.java).putExtra("username", username))
        }

        fetchCategories()
    }

    private fun showAddCategoryDialog() {
        val input = EditText(this)
        input.hint = "Enter category name"

        AlertDialog.Builder(this)
            .setTitle("Add Category")
            .setView(input)
            .setPositiveButton("Add") { dialog, _ ->
                val categoryName = input.text.toString().trim()
                if (categoryName.isNotEmpty()) {
                    addCategory(categoryName)
                } else {
                    Toast.makeText(this, "Category name cannot be empty", Toast.LENGTH_SHORT).show()
                }
                dialog.dismiss()
            }
            .setNegativeButton("Cancel") { dialog, _ -> dialog.cancel() }
            .show()
    }

    private fun addCategory(categoryName: String) {
        val db = FirebaseDatabase.getInstance()
        val categoriesRef = db.getReference("users/$username/Categories")

        // Create a new category with an autogenerated ID
        val newCategoryRef = categoriesRef.push()
        val category = Catagories(categoryName)
        newCategoryRef.setValue(category)
            .addOnSuccessListener {
                Toast.makeText(this, "Category added", Toast.LENGTH_SHORT).show()
                fetchCategories()
            }
            .addOnFailureListener {
                Toast.makeText(this, "Failed to add category: ${it.message}", Toast.LENGTH_SHORT).show()
            }
    }

    private fun fetchCategories() {
        val db = FirebaseDatabase.getInstance()
        val categoriesRef = db.getReference("users/$username/Categories")

        categoriesRef.get().addOnSuccessListener { snapshot ->
            categoryListLayout.removeAllViews()

            for (categorySnapshot in snapshot.children) {
                val category = categorySnapshot.getValue(Catagories::class.java)
                category?.let { addCategoryCard(it) }
            }
        }.addOnFailureListener {
            Toast.makeText(this, "Failed to load categories: ${it.message}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun addCategoryCard(category: Catagories) {
        val cardView = CardView(this).apply {
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            ).apply {
                setMargins(0, 0, 0, 16)
            }
            radius = 12f
            cardElevation = 4f
            setContentPadding(24, 24, 24, 24)

            // Set background color that contrasts with text
            setCardBackgroundColor(Color.parseColor("#FFFFFF")) // White background
        }

        val textView = TextView(this).apply {
            text = category.categoryName
            textSize = 18f
            setTextColor(Color.parseColor("#333333")) // Dark gray text
        }

        cardView.addView(textView)
        categoryListLayout.addView(cardView)
    }

}
